theme: jekyll-theme-minimal

title: Jacopo Panerati
description: Postdoctoral Fellow at the University of Toronto Institute for Aerospace Studies

logo: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=DzdTvkEAAAAJ&citpid=6
# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]

plugins:
  - jekyll-redirect-from
