theme: jekyll-theme-minimal

title: Jacopo Panerati
description: Postdoctoral Fellow at University of Toronto

# logo: [Location of the logo]
# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]

plugins:
  - jekyll-redirect-from
