theme: jekyll-theme-minimal

title: Jacopo Panerati
description: Postdoctoral Fellow at the University of Toronto Institute for Aerospace Studies

logo: https://github.com/JacopoPan/JacopoPan.github.io/blob/master/photo.jpeg?raw=true
# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]

plugins:
  - jekyll-redirect-from
